#!/bin/sh
# Copyright IBM Corp. 2008

JVM_EXTRA_CMD_ARGS=""

CHUTILS_DIR=`dirname $0`
. $CHUTILS_DIR/bin/setchutilsenv

if [ -f ${JAVA_HOME}/bin/java ]; then
    JAVA_EXE="${JAVA_HOME}/bin/java"
else
    JAVA_EXE="${JAVA_HOME}/jre/bin/java"
fi

if [ "$JVM_EXTRA_CMD_ARGS" != "" ]; then
    $JAVA_EXE $JVM_EXTRA_CMD_ARGS -classpath "$CHUTILS_CLASSPATH" com.ibm.ws.install.ni.chutils.ChUtils "$@"
else
    $JAVA_EXE -classpath "$CHUTILS_CLASSPATH" com.ibm.ws.install.ni.chutils.ChUtils "$@"
fi